### ISSUE TITLE
Skeleton issue

### ISSUE THREAD

**Issue by dj8yfo** [dj8yfo/app-near-rs#3]
# Various

- [x] https://github.com/dj8yfo/app-near-rs/pull/2

# Existing functionality
- [x] congruent behaviour on `INS_GET_PUBLIC_KEY` and `INS_GET_WALLET_ID` - https://github.com/dj8yfo/app-near-rs/pull/4
- [x] https://github.com/dj8yfo/app-near-rs/pull/5 , `assert_eq!(mem::size_of::<Transfer>, 16)`
- [x] `assert_eq!(mem::size_of::<TransactionPrefix>, 224)`
- [x] question: should `public_key`, `nonce`, `block_hash` fields of transaction prefix be displayed as well
- [x] https://github.com/dj8yfo/app-near-rs/pull/6 , `assert_eq!(mem::size_of::<CreateAccount>, 0)`
- [x] question: can `AccountId` be `Secp256K1PublicKey` representation as hex string 128 bytes long?
- [x] https://github.com/dj8yfo/app-near-rs/pull/7 , `assert_eq!(mem::size_of::<DeleteAccount>, 76)`
- [x] https://github.com/dj8yfo/app-near-rs/pull/8, `assert_eq!(mem::size_of::<DeleteKey>, 65)`
- [x] https://github.com/dj8yfo/app-near-rs/pull/9, `assert_eq!(mem::size_of::<Stake>, 88)`
- [x] https://github.com/dj8yfo/app-near-rs/pull/10, `assert_eq!(mem::size_of::<AddKey>, 88), assert_eq!(mem::size_of::<FunctionCallPermission>, 328)`
- [x] https://github.com/dj8yfo/app-near-rs/pull/11
- [x] https://github.com/dj8yfo/app-near-rs/pull/12, `assert_eq!(mem::size_of::<DeployContract>, 56)`
  - [x] TODO: add print of contract `Vec<u8>` SHA256 in `near-cli-rs`
- [x] https://github.com/dj8yfo/app-near-rs/pull/13, `assert_eq!(mem::size_of::<FunctionCallCommon>, 88)`, `assert_eq!(mem::size_of::<CappedString<200>>, 212)`
- [x] https://github.com/dj8yfo/app-near-rs/pull/14
- [x] https://github.com/dj8yfo/app-near-rs/pull/18
  - [x] https://github.com/dj8yfo/app-near-rs/pull/20

## advantages as compared to `app-near`
- [x] unlimited size of transactions
- [x] normal support of batch transactions, [test](https://github.com/dj8yfo/app-near-rs/blob/develop/tests/test_sign_transaction/test_batch_transaction.py), [screenshots of 2/12 action](https://github.com/dj8yfo/app-near-rs/tree/develop/tests/snapshots/nanos/test_sign_batch_transaction_all_actions/2_0_next_action) ,  none of the details of actions are shown in [`app-near`](https://github.com/LedgerHQ/app-near/tree/develop/workdir/app-near/tests/snapshots/nanos/test_sign_multiple_actions_2_apdu_exchanges)  
## comparison of details shown with `app-near`
  
  - [x] [`CreateAccountAction`](https://docs.rs/near-primitives/0.20.1/near_primitives/action/struct.CreateAccountAction.html)
    - [x] no change
- [x] [`DeleteAccountAction`](https://docs.rs/near-primitives/0.20.1/near_primitives/action/struct.DeleteAccountAction.html)
  - [x] cargo run --example sign_delete_account_{short,long}
    - [x] Beneficiary ID action field not displayed in `app-near`
 - [x] [`DeleteKeyAction`](https://docs.rs/near-primitives/0.20.1/near_primitives/action/struct.DeleteKeyAction.html)
   - [x] cargo run --example sign_delete_key_{ed25519/secp256k1}
     - [x] Public Key action field not displayed in `app-near`
- [x] [`StakeAction`](https://docs.rs/near-primitives/0.20.1/near_primitives/action/struct.StakeAction.html)
  - [x] cargo run --example sign_stake
    - [x] Stake and Public Key fields of action not displayed in `app-near`
- [x] [`TransferAction`](https://docs.rs/near-primitives/0.20.1/near_primitives/action/struct.TransferAction.html)
  - [x] cargo run --example sign_transfer
    - [x] no change
- [x] [`AddKeyAction`](https://docs.rs/near-primitives/0.20.1/near_primitives/action/struct.AddKeyAction.html)
  - [x] cargo run --example sign_add_key_fullaccess
    - [x] Public Key field and access_key.Nonce field of action is not displayed in `app-near`
  - [x] cargo run --example sign_add_key_functioncall
    - [x] `app-near` displays this case identical to Full Access one (Public Key field and access_key.Nonce field of action is not displayed, no details show on Function Call Permission)
- [x] [DeployContractAction](https://docs.rs/near-primitives/0.20.1/near_primitives/action/struct.DeployContractAction.html)
  - [x] cargo run --example sign_deploy_contract
    - [x] `code` field of action not displayed in `app-near`; sha256 of `code` field is displayed in `app-near-rs`
- [x] [`FunctionCallAction`](https://docs.rs/near-primitives/0.20.1/near_primitives/action/struct.FunctionCallAction.html)
  - [x] `gas` field of action isn't displayed in `app-near` (string `args` argument)
  - [x] `gas` field of action isn't diplayed, binary `args` argument displayed as blank in `app-near`

# New functionality
- [x] https://github.com/dj8yfo/app-near-rs/pull/15
- [x] https://github.com/dj8yfo/app-near-rs/pull/16
- [x] https://github.com/dj8yfo/app-near-rs/pull/19
  - [x] https://github.com/dj8yfo/app-near-rs/pull/21
## `nep-413` message protocol
The protocol is similar to regular transaction signing, which has 20 bytes of 5-component [BIP32Path](https://docs.rs/slip10/latest/slip10/path/struct.BIP32Path.html) followed by `borsh` serialization of transaction transferred over multiple apdu messages. There're two differences:

1. instruction byte in all of apdu headers is changed from `2` -> `7`
```rust
const INS_SIGN_TRANSACTION: u8 = 2; // Instruction code to sign a transaction on the Ledger
const INS_SIGN_NEP413_MESSAGE: u8 = 7; // Instruction code to sign a nep-413 message with Ledger
```
2. 20 bytes of 5-component [BIP32Path](https://docs.rs/slip10/latest/slip10/path/struct.BIP32Path.html) are followed by `borsh` serialization of `NEP413Payload`: 
```rust
pub struct NEP413Payload {
    pub messsage: String,
    pub nonce: [u8; 32],
    pub recipient: String,
    pub callback_url: Option<String>,
}
```
Sample code which forms and sends such a message is targeted by this [link](https://github.com/dj8yfo/near-ledger-rs/blob/more_examples/examples/sign_nep_413_message.rs). 

## `nep-366` message protocol
The protocol is similar to regular transaction signing, which has 20 bytes of 5-component [BIP32Path](https://docs.rs/slip10/latest/slip10/path/struct.BIP32Path.html) followed by `borsh` serialization of transaction transferred over multiple apdu messages. There're two differences:

1. instruction byte in all of apdu headers is changed from `2` -> `8`
```rust
const INS_SIGN_TRANSACTION: u8 = 2; // Instruction code to sign a transaction on the Ledger
const INS_SIGN_NEP366_DELEGATE_ACTION: u8 = 8; // Instruction code to sign a nep-366 delegate action with Ledger
```
2. 20 bytes of 5-component [BIP32Path](https://docs.rs/slip10/latest/slip10/path/struct.BIP32Path.html) are followed by `borsh` serialization of [`DelegateAction`](https://docs.rs/near-primitives/0.20.1/near_primitives/action/delegate/struct.DelegateAction.html): 
```rust
pub struct DelegateAction {
    /// Signer of the delegated actions
    pub sender_id: AccountId,
    /// Receiver of the delegated actions.
    pub receiver_id: AccountId,
    /// List of actions to be executed.
    ///
    /// With the meta transactions MVP defined in NEP-366, nested
    /// DelegateActions are not allowed. A separate type is used to enforce it.
    pub actions: Vec<NonDelegateAction>,
    /// Nonce to ensure that the same delegate action is not sent twice by a
    /// relayer and should match for given account's `public_key`.
    /// After this action is processed it will increment.
    pub nonce: Nonce,
    /// The maximal height of the block in the blockchain below which the given DelegateAction is valid.
    pub max_block_height: BlockHeight,
    /// Public key used to sign this delegated action.
    pub public_key: PublicKey,
}
pub type Nonce = u64;
pub type BlockHeight = u64;
```
Sample code which forms and sends such a message is targeted by this [link](https://github.com/dj8yfo/near-ledger-rs/blob/more_examples/examples/sign_nep_366_delegate_action.rs). 
# CI/Ragger tests
<details>
  <summary>details</summary>
  
  
- [x] https://github.com/dj8yfo/app-near-rs/pull/22
- [x] https://github.com/dj8yfo/app-near-rs/pull/23
- [x] https://github.com/dj8yfo/app-near-rs/pull/24
- [x] https://github.com/dj8yfo/app-near-rs/pull/26
- [x] https://github.com/dj8yfo/app-near-rs/pull/27
- [x] https://github.com/dj8yfo/app-near-rs/pull/28
- [x] https://github.com/dj8yfo/app-near-rs/pull/29
- [x] https://github.com/dj8yfo/app-near-rs/pull/30
- [x] https://github.com/dj8yfo/app-near-rs/pull/31
- [x] https://github.com/dj8yfo/app-near-rs/pull/32
- [x] https://github.com/dj8yfo/app-near-rs/pull/33
- [x] https://github.com/dj8yfo/app-near-rs/pull/34
- [x] https://github.com/dj8yfo/app-near-rs/pull/37
- [x] https://github.com/dj8yfo/app-near-rs/pull/38
- [x] https://github.com/dj8yfo/app-near-rs/pull/39
- [x] https://github.com/dj8yfo/app-near-rs/pull/40

</details>

# Encountered issues:
- [x] https://github.com/LedgerHQ/ledger-device-rust-sdk/issues/122
- [ ] non-ASCII chars aren't supported by SDK: as indicated by https://github.com/LedgerHQ/ledger-device-rust-sdk/pull/120#discussion_r1465001033, attempting to work with non-ASCII strings will undeterministically result in either app crashes or displaying blanks instead of parts of strings. Suggestion was made to declare explicit support of `ASCII`-only in https://github.com/LedgerHQ/ledger-device-rust-sdk/issues/124.
  - [x] non-ASCII chars not supported by C sdk as well
  - [ ] SDK works with newlines present in msgs, but appears to be skipping small chunks of msgs, when newlines are present
    - [x] this was formally described by issue https://github.com/LedgerHQ/ledger-device-rust-sdk/issues/146
    
These https://github.com/LedgerHQ/ledger-device-rust-sdk/issues/124 and https://github.com/LedgerHQ/ledger-device-rust-sdk/issues/146 haven't been resolved yet, but have been worked around by https://github.com/dj8yfo/app-near-rs/pull/47

**Comment by frol** [comment]
> question: should public_key, nonce, block_hash fields of transaction prefix be displayed as well

Nah, it is useless for users. Public key has to match the private key on Ledger, so you may validate this and it would be better than asking user to do that.

> question: can AccountId be Secp256K1PublicKey representation as hex string 128 bytes long?

Nope, but before you asked, I have never thought that NEAR doesn't support implicit accounts with keys different than ed25519.

**Comment by dj8yfo** [comment]
> SDK works with newlines present in msgs, but appears to be skipping small chunks of msgs, when newlines are present

https://github.com/LedgerHQ/ledger-device-rust-sdk/issues/146

**Comment by dj8yfo** [comment]
mentioned in README
