### ISSUE TITLE
NEAR amounts display

### ISSUE THREAD

**Issue by frol** [dj8yfo/app-near-rs#36]
Looking at the tests, I didn’t see a test for 1 yoctoNEAR deposit, which is quite common pattern in NEAR to require the transaction to be signed with a full access key. There are also a few other corner cases, so here is the list of suggested test cases for the NEAR amounts:

* [ ] 1 yoctoNEAR (function call)
* [ ] 1M NEAR - often used in delegation to stake (function call, transfer, stake actions)
* [ ] 0.00001 NEAR - often used to deposit for storage (function call)
* [ ] 1234.56 NEAR - often used for regular transfers

**Comment by dj8yfo** [comment]
resolved by #42
